// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5C4HPHdJKQEBNrhzasG_u-AJMRWLErTE',
    appId: '1:900715475478:web:05cb9c17e83d5014c4bb37',
    messagingSenderId: '900715475478',
    projectId: 'infantry-house',
    authDomain: 'infantry-house.firebaseapp.com',
    storageBucket: 'infantry-house.firebasestorage.app',
    measurementId: 'G-258HTVEHFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeoAu_S0sZJTDB7O_A8HnYlzn2OMOQzmc',
    appId: '1:900715475478:android:2c3c3b111df59ef0c4bb37',
    messagingSenderId: '900715475478',
    projectId: 'infantry-house',
    storageBucket: 'infantry-house.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlWc2TM0EqbUOe6NqNAx09rfW-vDN8Zy0',
    appId: '1:900715475478:ios:69bbe17e0e76e154c4bb37',
    messagingSenderId: '900715475478',
    projectId: 'infantry-house',
    storageBucket: 'infantry-house.firebasestorage.app',
    iosBundleId: 'com.example.infantryHouseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlWc2TM0EqbUOe6NqNAx09rfW-vDN8Zy0',
    appId: '1:900715475478:ios:69bbe17e0e76e154c4bb37',
    messagingSenderId: '900715475478',
    projectId: 'infantry-house',
    storageBucket: 'infantry-house.firebasestorage.app',
    iosBundleId: 'com.example.infantryHouseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5C4HPHdJKQEBNrhzasG_u-AJMRWLErTE',
    appId: '1:900715475478:web:efd0b542cdadfc82c4bb37',
    messagingSenderId: '900715475478',
    projectId: 'infantry-house',
    authDomain: 'infantry-house.firebaseapp.com',
    storageBucket: 'infantry-house.firebasestorage.app',
    measurementId: 'G-W294J6WR7L',
  );

}