name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java (required for Android builds)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.29.2
          channel: stable
          cache: true
          architecture: X64
          pub-cache-path: default
          dry-run: false
          git-source: https://github.com/flutter/flutter.git


        #ceate key store file and key.properties
      - name: Create keystore file
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/upload-keystore.jks
        working-directory: ./android

      - name: Create key.properties file
        run: |
          cat << EOF > key.properties
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=upload-keystore.jks
          EOF
        working-directory: ./android

      # Get dependencies
      - name: Install dependencies
        run: flutter pub get

#      # Run tests
#      - name: Run tests
#        run: flutter test

      # Build AAB
      - name: Build AAB
        run: flutter build appbundle --release

      # Upload APK to Google Drive
      - name: Upload APK to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          filename: build/app/outputs/flutter-apk/app-release.apk
          folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          name: infantry_house_app-release.apk
          overwrite: true