name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java (required for Android builds)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.29.2
          channel: stable
          cache: true
          architecture: X64
          pub-cache-path: default
          dry-run: false
          git-source: https://github.com/flutter/flutter.git

      # Get dependencies
      - name: Install dependencies
        run: flutter pub get

#      # Run tests
#      - name: Run tests
#        run: flutter test

      # Build APK
      - name: Build APK
        run: flutter build apk --release

      # Upload APK to Google Drive
      - name: Upload APK to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          filename: build/app/outputs/flutter-apk/app-release.apk
          folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          name: infantry_house_app-release.apk